name = "best-before"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[dev]
port = 3000

[[d1_databases]]
binding = "DB"
database_name = "best-before"
database_id = "11c4acd9-b9b4-4f1c-80b2-2369c49c0f8c"

[[d1_databases]]
binding = "PREVIEW_DB"
database_name = "best-before-preview"
database_id = "153a209c-48e8-4bcc-92fa-6c1390104290"
